class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_action :configure_permitted_parameters, if: :devise_controller?


protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   devise_parameter_sanitizer.permit(:account_update, keys: [:name])

	devise_parameter_sanitizer.permit(:sign_up, keys: [:q1])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q1])
	   devise_parameter_sanitizer.permit(:sign_up, keys: [:q2])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q2])
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q2a])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q2a])
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q2b])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q2b])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:q2c])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q2c])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:q2d])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q2d])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:q2e])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q2e])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:q3])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q3]) 
      devise_parameter_sanitizer.permit(:sign_up, keys: [:q4])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q4]) 
      devise_parameter_sanitizer.permit(:sign_up, keys: [:q5])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q5]) 
    devise_parameter_sanitizer.permit(:sign_up, keys: [:q6a])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q6a]) 
    devise_parameter_sanitizer.permit(:sign_up, keys: [:q6b])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q6b]) 
    devise_parameter_sanitizer.permit(:sign_up, keys: [:q6c])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q6c]) 
    devise_parameter_sanitizer.permit(:sign_up, keys: [:q67])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q67])   
    devise_parameter_sanitizer.permit(:sign_up, keys: [:q8])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q8]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q9])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q9]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q10])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q10]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q11])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q11]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q12])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q12]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q13])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q13]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q14])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q14]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q15])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q15]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q16])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q16]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q17])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q17]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q18])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q18]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q19])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q19]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q20])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q20]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q21])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q21]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q22])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q22])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:q22a])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q22a])
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q23])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q23]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q24])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q24]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q25])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q25]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q26])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q26])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:q27])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q27]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q28])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q28]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q29])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q29]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q30])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q30]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q31])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q31]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q32])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q32])
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q33])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q33]) 
        devise_parameter_sanitizer.permit(:sign_up, keys: [:q34])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q34])
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q35])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q35]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q36])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q36]) 
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q37])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q37])
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q38])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q38]) 
        devise_parameter_sanitizer.permit(:sign_up, keys: [:q39])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q39])
       devise_parameter_sanitizer.permit(:sign_up, keys: [:q40])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q40]) 
        devise_parameter_sanitizer.permit(:sign_up, keys: [:q41])
   devise_parameter_sanitizer.permit(:account_update, keys: [:q41]) 


 end
end